package:
  name: r-rintaros
  version: 1.3 

source:
  path: ../src

build:
  # If this is a new build for the same version, increment the build number.
  number: 3
  
  script_env:
    - LD_LIBRARY_PATH # [linux]

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base 3.5

  run:
    - r-base 3.5
    - r-rgeostats >=11.2.11
    - r-maps

test:
  commands:
    - $R -e "library('RIntaros')"

about:
  home: http://rgeostats.free.fr/
  license: GPL v3
  summary: Interface between RGeostats and Intaros 

