{% set version = '1.7' %}

package:
  name: r-rintaros
  version: {{ version|replace("-", "_") }} 

source:
  fn: RIntaros_{{ version }}_linux64.tar.gz
  url:
    - http://cg.ensmp.fr/rgeos/DOWNLOAD/RIntaros_{{ version }}_linux64.tar.gz

  sha256: 3ba42c5d096a37d5d7a4104e35efd3b6532e34402c5dad964000971433d12c0a

build:
  # If this is a new build for the same version, increment the build number.
  number: 1
  
  script_env:
    - LD_LIBRARY_PATH # [linux]

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base 3.5

  run:
    - r-base 3.5
    - r-rgeostats >=11.2.11
    - r-maps >=3.0.0

test:
  commands:
    - $R -e "library('RIntaros')"

about:
  home: http://cg.ensmp.fr/rgeostats
  license: GPL v3
  summary: Interface between RGeostats and Intaros 

