{% set version = '1.5' %}

package:
  name: r-rintaros
  version: {{ version|replace("-", "_") }} 

source:
  fn: RIntaros_{{ version }}_linux64.tar.gz
  url:
    - http://cg.ensmp.fr/rgeos/DOWNLOAD/RIntaros_{{ version }}_linux64.tar.gz

  sha256: a195e748b3f92360054e8576976fa60a6e81b9a9ae97558f0fc2c57fda9f7463

build:
  # If this is a new build for the same version, increment the build number.
  number: 2
  
  script_env:
    - LD_LIBRARY_PATH # [linux]

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base 3.5

  run:
    - r-base 3.5
    - r-rgeostats >=11.2.11
    - r-maps >=3.0.0

test:
  commands:
    - $R -e "library('RIntaros')"

about:
  home: http://cg.ensmp.fr/rgeostats
  license: GPL v3
  summary: Interface between RGeostats and Intaros 

